config/urls.py
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('helloworld/', include('kadai503.urls')),
    path('fruits/', include('kadai504.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kadai503/urls.py
from django.urls import path
from .views import helloworldfunction, get_list

urlpatterns = [
    path('today/', helloworldfunction),
    path('list/', get_list),
]

kadai504/urls.py
from django.urls import path
from . import views

app_name = 'fruits'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.DeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.UpdateView.as_view(), name='update'),
]

kadai504/models.py
from django.db import models
from django.core.validators import MinValueValidator, MinLengthValidator, MaxLengthValidator

# Create your models here.
class Fruits(models.Model):
    no = models.IntegerField(
        'No.',
        validators=[MinValueValidator(1, 'Noは1以上を入力してください')]
        )
    name = models.CharField(
        '果物名',
        max_length=255, 
        validators=[MaxLengthValidator(10, '果物名は10文字以内で入力してください')])
    memo = models.TextField(
        'メモ',
        blank=True,
        max_length=50,
        validators=[MinLengthValidator(5, 'メモは5～50文字で入力してください')])

    def __str__(self):
        return self.name

    

kadai504/forms.py
from django.forms import fields
from .models import Fruits
from django import forms

class FruitsForm(forms.ModelForm):
    class Meta:
        model = Fruits
        fields = '__all__'
        labels = {
            'no':'No.',
            'name':'果物名',
            'memo':'メモ',
            }

kadai503/views.py
# from config.settings import TEMPLATES
from django.shortcuts import render

from django.http import HttpResponse
from datetime import date


# Create your views here.
def helloworldfunction(request):
    today = date.today()
    todaystr = today.strftime('%Y/%m/%d %A')
    context = {'date': todaystr}
    return render(request, 'hello.html', context)

def get_list(request):
    fruitlist = [
        ['メロン', '高い'],
        ['リンゴ', 'おいしいよ'],
        ['マスカット', 'つぶつぶです'],
        ['アケビ', 'おいしいよ'],
        ['アセロラ', 'ビタミンたくさん'],
        ['アボカド', '栄養あるよ'],
        ['アンズ(杏)', 'おいしいよ'],
        ['イチゴ', 'ビタミンたくさん'],
        ['イチジク', '栄養あるよ'],
        ['ウメ(梅)', 'おいしいよ'],
        ['温州ミカン(みかん)', 'ビタミンたくさん'],
        ['オレンジ', '栄養あるよ'],
        ['カキ(柿)', 'おいしいよ'],
        ['カリン', 'ビタミンたくさん'],
        ['カンキツ類', '栄養あるよ'],
        ['キウイフルーツ', 'おいしいよ'],
        ['キワノ', 'ビタミンたくさん'],
        ['クリ(栗)', '栄養あるよ'],
        ['グアバ', 'おいしいよ'],
        ['グレープフルーツ', 'ビタミンたくさん'],
        ['香酸柑橘', '栄養あるよ'],
        ['サクランボ(桜桃)', 'おいしいよ'],
        ['ザクロ', 'ビタミンたくさん'],
        ['スイカ(西瓜)', '栄養あるよ'],
        ['スターフルーツ', 'おいしいよ'],
        ['スモモ(プラム)', 'ビタミンたくさん'],
        ['西洋ナシ(西洋梨)', '栄養あるよ'],
        ['チェリモヤ', 'おいしいよ'],
        ['中国ナシ(中国梨)', 'ビタミンたくさん'],
        ['ドラゴンフルーツ', '栄養あるよ'],
        ['ドリアン', 'おいしいよ'],
        ['ナシ(日本梨)', 'ビタミンたくさん'],
        ['ネクタリン', '栄養あるよ'],
        ['バナナ', 'おいしいよ'],
        ['パイナップル', 'ビタミンたくさん'],
        ['パッションフルーツ', '栄養あるよ'],
        ['パパイア', 'おいしいよ'],
        ['ビワ(枇杷)', 'ビタミンたくさん'],
        ['ブドウ(葡萄)', '栄養あるよ'],
        ['ブルーベリー', 'おいしいよ'],
        ['プルーン', 'ビタミンたくさん'],
        ['ベリー類', '栄養あるよ'],
        ['マルメロ', 'おいしいよ'],
        ['マンゴスチン', 'ビタミンたくさん'],
        ['マンゴー', '栄養あるよ'],
        ['メロン', 'おいしいよ'],
        ['モモ(桃)', 'ビタミンたくさん'],
        ['ライチ（レイシ）', '栄養あるよ'],
        ['リンゴ', 'おいしいよ'],
        ['レモン', 'ビタミンたくさん'],
    ]
    listnum = get_listnum(fruitlist)
    context = {
        'fruit' : fruitlist,
        'listnum' : listnum,
    }
    return render(request, 'list.html', context)

def get_listnum(list):
    listnum = len(list)
    return listnum 

kadai504/views.py
from kadai504.models import Fruits
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Fruits
from .forms import FruitsForm

# Create your views here.

class IndexView(generic.ListView):
    model = Fruits
    template_name = 'fruits/index.html'


class CreateView(generic.edit.CreateView):
    model = Fruits
    # form = FruitsForm()
    fields = ('no', 'name', 'memo')
    template_name = 'fruits/create.html'
    success_url = "/fruits/"


class DetailView(generic.DetailView):
    model = Fruits
    fields = ('no', 'name', 'memo')
    template_name = 'fruits/detail.html'


class DeleteView(generic.edit.DeleteView):
    model = Fruits
    template_name = 'fruits/delete.html'
    success_url = reverse_lazy('fruits:index')


class UpdateView(generic.edit.UpdateView):
    model = Fruits
    fields = ('no', 'name', 'memo')
    template_name = 'fruits/update.html'

templates/fruits/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>{% block title %}一覧{% endblock %}</title>
  </head>
  <body>
    <div class="container">
        {% block content %}
            {{ content }}
        {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/fruits/create.html
{% extends 'fruits/base.html' %}

{% block title %}
新規作成
{% endblock %}

{% block content %}
    <h1>新規登録</h1>
    <form method="post">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <button type="submit" class="submit btn btn-info">登録</button>
    </form>
    <br/>
    <a href="{% url 'fruits:index' %}" class="btn btn-info">キャンセル</a>
{% endblock %}

templates/fruits/delete.html
{% extends 'fruits/base.html' %}

{% block title %}
削除
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr><td>No. ：</td><td>{{ object.no }}</td></tr>
            <tr><td>果物名：</td><td>{{ object.name }}</td></tr>
            <tr><td>メモ：</td><td>{{ object.memo }}</td></tr>
            <br/>
        </table>
        <br/>
        <br/>
        <button type="submit" class="submit delete btn btn-danger">削除</button>
    </form>
    <br/>
    <a href="{% url 'fruits:index' %}" class="btn btn-info">キャンセル</a>
{% endblock %}

templates/fruits/detail.html
{% extends 'fruits/base.html' %}

{% block title %}
詳細
{% endblock %}

{% block headertitle %}
詳細
{% endblock %}

{% block content %}
    <div>
        <table class="table table-sm">
            <tr><td>No</td><td>{{ object.no }}</td></tr>
            <tr><td>果物名</td><td>{{ object.name }}</td></tr>
            <tr><td>メモ</td><td>{{ object.memo }}</td></tr>
        </table>
        <br/>
    </div>
    <br/>
    <a href="{% url 'fruits:index' %}" class="btn btn-info">戻る</a>
{% endblock %}

templates/fruits/index.html
{% extends 'fruits/base.html' %}

{% block title %}
一覧
{% endblock %}

{% block content %}
<h1>一覧</h1>
  <table class="table table-striped table-bordered　table-sm">
    <thead>
      <tr>
        <th>No.</th>
        <th>果物名</th>
        <th>メモ</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for fruits in object_list %}
      <tr>
        <td>{{ fruits.no }}</td>
        <td>{{ fruits.name }}</td>
        <td>{{ fruits.memo }}</td>
        <td>
          <a href="{% url 'fruits:detail' fruits.pk %}" class="btn btn-info btn-sm">詳細</a>
          <a href="{% url 'fruits:update' fruits.pk %}" class="btn btn-info btn-sm">更新</a>
          <a href="{% url 'fruits:delete' fruits.pk %}" class="btn btn-info btn-sm">削除</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'fruits:create' %}" class="btn btn-primary btn-sm">追加</a>
{% endblock %}

templates/fruits/update.html
{% extends 'fruits/base.html' %}

{% block title %}
更新
{% endblock %}

{% block headertitle %}
更新
{% endblock %}

{% block content %}
  <form action="" method="post">
      {% csrf_token %}
      <table>{{ form.as_table }}</table>
      <button type="submit" class="submit btn btn-info">更新</button>
  </form>
  <br/>
  <a href="{% url 'fruits:index' %}" class="btn btn-info">キャンセル</a>
{% endblock %}

templates/hello.html
<p>today is {{ date }}</p>

templates/list.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>フルーツリスト</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  </head>
  <body>
    <p>fruits</p>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">果物名</th>
            <th scope="col">メモ</th>
          </tr>
        </thead>
        <tbody>
          {% for f in fruit %}
            <tr>
              <th></th>
              {% for item in f %}
              <td>{{ item }}</td>
              {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>

      {% if listnum > 0 %}
      <p>全{{ listnum }}件</p>
      {% endif %}
      
        <ul class="example">
        <li>1</li>
        <li><a href="/page/2/">2</a></li>
        <li><a href="/page/3/">3</a></li>
        <li><a href="/page/2/" rel="next">次へ</li>
        </ul>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>